declare module '@digitalcredentials/vc';
declare module '@digitalcredentials/vpqr';
declare module '@digitalcredentials/ed25519-verification-key-2020';
declare module '@digitalcredentials/ed25519-signature-2020';
declare module '@digitalcredentials/security-document-loader';
declare module '@digitalcredentials/vc-bitstring-status-list';
declare module '@digitalcredentials/vc-status-list';
declare module 'jsonld-signatures';
declare module 'uuid';
