declare module '@digitalbazaar/vc';
declare module '@digitalbazaar/vpqr';
declare module '@digitalbazaar/ed25519-verification-key-2020';
declare module '@digitalbazaar/ed25519-signature-2020';
declare module '@digitalcredentials/security-document-loader';
declare module '@digitalbazaar/vc-bitstring-status-list';
declare module '@digitalbazaar/vc-status-list';
declare module 'jsonld-signatures';
declare module 'uuid';
